spring:
  datasource:
    url: jdbc:mysql://47.96.89.84:3306/btbs_user?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: MiZhi001