spring:
  datasource:
    url: jdbc:mysql://121.199.24.90:3306/tcl_user?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: 123JSGBSH..jsgbsh
