server:
  port: 9090
  address: 0.0.0.0
spring:
  datasource:
    #数据库ip及库名
    url: jdbc:mysql://121.199.24.90:3306/tcl_user?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root #账号
    password: 123JSGBSH..jsgbsh  #密码
